// tldr-github-parcel/src/App.tsx
import * as React from "react";
import { Repo } from "./Repo";
import { useState, useEffect } from "react";

export function App(): JSX.Element {
  let [repos, setRepos] = useState([]);

  useEffect(() => {
      const getData = async (): Promise<void> => {
          const response = await fetch('/api/repos');
          repos = await response.json();
          setRepos(repos)
      };
      getData();
  }, []);

  if (repos.length === 0) {
    return (
      <div className="px-20 py-20">
        <p className="text-center subtle">No repos added yet</p>
      </div>
    );
  }

  return (
    <div className="px-20 py-20">
      <div className="grid">
        {repos.map(repo => (
          <Repo repo={repo} />
        ))}
      </div>{" "}
    </div>
  );
}

// tldr-github-svelte/src/App.svelte
<script>
  import Repo from './Repo.svelte';
  import AddRepo from './AddRepo.svelte';
  import { onMount } from 'svelte';

  let repos = []

  const fetchRepos = async () => {
      const response = await fetch('/api/repos');

      repos = await response.json();
  }

  onMount(fetchRepos)

</script>

{#if repos.length === 0}
  <p>No repos added yet</p>
{/if}
<div class="grid">
  {#each repos as repo, index}
    <Repo repo={repo} />
  {/each}
  <AddRepo on:new-repo-added={fetchRepos} />
</div>
